.dockerignore, .github/workflows/deploy_dev.yml, Dockerfile, compose.yml, next.config.ts
AWS EC2, NCP 그리고 github actions ci/cd 설정
> #13 CI/CD
> NCP Container Registry에 도커 이미지 푸시
> 서버에서 이미지 풀
> 도커 파일 작성, 컴포즈 파일 작성
> 서버 내 컴포즈 파일 작성
> NCP 서버, Container Registry 설정
> 제발.....!
=> 🚀 배포 및 ci/cd

.github/workflows/deploy_dev.yml
> ex) #13
> github workflow 파일 수정
> 도커 이미지 NCP에 푸시하기 이전에 태그 달아줌
> 여전히 확실하지 않음
=> 💚 CI/CD 버그 수정

.github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml
> ex) #13 
> 이미지 및 컨테이너 이름 수정
> 프로덕션 CI/CD 잠시 주석 처리
> 최최종
=> 💚 타이포 수정 밒 프로덕션 CI/CD 주석 처리

.github/workflows/deploy_prod.yml
> ex) #13 
> 이미지, 컨테이너 이름 정리
> 제발 그만............
=> 💚 이미지, 컨테이너 정리

package-lock.json, src/app/(main)/private-jobs/PriviteJobsPage.tsx, src/app/(main)/public-jobs/PublicJobsPage.tsx, src/components/ui/button.tsx, src/components/ui/pagination.tsx
=> 💄 페이지네이션 샤드씨엔

src/app/layout.tsx, src/store/SwrProvider.tsx
axios 인스턴스 완료 시 업데이트
> ex) #73 
> SWR 전역설정 (config) 추가 (store 폴더)
> axios 인스턴스가 완료된 후, 업데이트가 필요함.
=> ✨ SWR 전역 설정 추가

.github/workflows/deploy_dev.yml, Dockerfile
> ex) 환경 변수 추가 설정 변경
> 도커파일, 깃헙액션스 yml
>
=> 💚 환경 변수 설정 변경

.github/workflows/deploy_dev.yml, Dockerfile, src/app/(main)/private-jobs/PrivateJobsPage.tsx, src/app/(main)/public-jobs/PublicJobsPage.tsx
보안 + 작동 확신
> ex) #86 
> 전부 다 NEXT_PUBLIC_ 방식으로 클라이언트에서도 접근할 수 있지만,
> EC2에 직접 넣어줘서, 이미지 자체에 노출되지 않게 함.
> 최최최종 확신
=> 🔐 환경변수 설정 최종

src/app/(main)/private-jobs/PrivateJobsPage.tsx, src/app/(main)/public-jobs/PublicJobsPage.tsx
=> 🐛 내부 주소 적용

.github/workflows/deploy_dev.yml, src/components/chatbot/ChatbotPopup.tsx
웹소켓 로컬, 배포주소 환경변수 적용
> ex) #104 
> 웹소켓 로컬주소, 배포주소 환경변수 적용했습니다.
>
=> ✨ 웹소켓 로컬, 배포주소 환경변수 적용

src/components/chatbot/ChatbotPopup.tsx
=> 🧪 환경 변수 셋 다 체크

.github/workflows/build_verification.yml, Dockerfile
> ex) #75 
> 도커 이미지 노드 버전 수정
> 배포 제발 그만 ㅋㅋㅋ
=> 🐛 이미지 노드 버전 수정

src/components/chatbot/ChatbotPopup.tsx
채팅말풍선 내 줄바꿈 적용
> ex) #114 
> 채팅창 내부 말풍선 안에서 줄바꿈하도록 태그 수정했습니다. pre 태그는 글자 사이 간격이 너무 넓어져서 div 로 수정하고 스타일 수정해서 반영했습니다!
>
=> ✨ 채팅말풍선 내 줄바꿈 적용

src/api/user.ts, src/components/header/Header.tsx
> ex) #124
> 미루고 미뤄왔던... 로그인 상태에따라 헤더 오른쪽 버튼 바뀌게 했슴당~ + 로그아웃 api연결 했어욤
>
=> 📝 헤더 렌더링 수정, 로그아웃 api 연결

src/components/common/text-editor/JobPostingEditor.tsx, src/components/common/text-editor/TogleButton.tsx, src/components/common/text-editor/style-options/ImageUploadBtn.tsx, src/components/job-posting/JobPostingForm.tsx, src/lib/fetcher.ts, src/types/Schema/jobPostingSchema.ts
> ex) #127 
> 이미지 업로드 기능 추가 (fetcher 함수 살짝 수정함)
> 공고 작성 API 연결
>
=> ✨ 공고 작성 API 연결 및 이미지 업로드 구현

src/app/(auth)/(dashboard)/company-dashboard/job-postings/post/page.tsx, src/app/(auth)/(dashboard)/dashboard/resume/post/page.tsx, src/components/common/text-editor/style-options/ImageUploadBtn.tsx, src/components/job-posting/JobPostingForm.tsx, src/components/resume/ResumeForm.tsx, src/types/Schema/jobPostingSchema.ts, src/types/Schema/resumeSchema.ts
아직 미완성
> ex) #132 
> 이력서 작성 컴포넌트 작성
> 경력, 학력, 이미지 미완성
> 이력서 스키마 및 타입 설정
>
=> 💄 이력서 작성 레이아웃 추가

src/components/common/text-editor/CharacterCounter.tsx, src/components/common/text-editor/JobPostingEditor.tsx, src/components/common/text-editor/JobPostingViewer.tsx, src/components/job-posting/JobPosting.tsx, src/components/job-posting/JobPostingForm.tsx, src/types/Schema/jobPostingSchema.ts
> ex) #151 
> 공고 상세 페이지 구현
> id를 전달하면 페칭해와서 렌더링
> 드디어...
=> 공고 상세 페이지 조회

src/components/admin/chatbot/ChatbotAdminClient.tsx, src/components/admin/chatbot/ChatbotModal.tsx, src/components/admin/user/UserTable.tsx, src/components/admin/user/columns.tsx
챗봇관리, 회원관리 fetch방식 리팩토링
> ex) #168 
> 챗봇관리, 회원관리 fetch방식 리팩토링하고 SWR 방식으로 통일했습니다. 
>
=> 🔧 챗봇관리, 회원관리 fetch방식 리팩토링

README.md
=> ✨ Feat: readme 업데이트

src/app/(auth)/dashboard/job-seeker/job-postings/favorite/[id]/page.tsx, src/components/job-posting/ApplyButton.tsx, src/components/job-posting/ResumeListModal.tsx
지원한 전체 공고 조회 오류 있음
> ex) #197 
> 찜한 공고 지원하기 수정
> 아직 제대로 테스트 불가
> 지원한 공고 전체 조회하기 API에 에러가... 500
> (없던건데 로그보면 백엔드에서 이미지url 관련 무언가가 잘못된것으로 추정)
>
=> ✨ 찜한 공고 지원하기 수정

src/components/job-posting/JobPosting.tsx
JobPosting 컴포넌트 작성일, 수정일 조건부 추가
> ex) #250 
>  JobPosting 컴포넌트 작성일, 수정일 조건부 추가
>
=> 🧱 JobPosting 컴포넌트 작성일, 수정일 조건부 추가

src/app/(auth)/dashboard/business/profile/page.tsx, src/app/(auth)/user/edit/_components/UserEditPageClient.tsx, src/app/layout.tsx, src/components/common/likebutton/LikePlusModal.tsx, src/components/common/likebutton/LikedButton.tsx, src/components/common/modals/LoginRequiredModal.tsx, src/components/header/Header.tsx, src/store/SwrProvider.tsx, src/store/useAuthStore.ts, src/store/useLoginModalStore.ts, src/types/user.ts
=> 🐛 마지막 수정 ㅠㅠㅠㅠㅠㅠㅠㅠㅠ
